### ISSUE TITLE
Safe Cracker A custom event suggested by dayle

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#114]
Submitted by **Filid**

**Comment by FilidDamhsoir** [comment]
@Filid Here's an idea based on a game we played on my trip to the lakes (i was planning on using it in the Duskrift Games) I call it safe cracker, what you have is a big safe (convieniently   containing an equal amount of loot for all participating team members) and the goal is for each team to go looking for clues to solve the combination.
The combination could be a numeric one say 63791 and people would find clues like "the 3rd number is 7" or "9 is next to one"
The combination could also be a word like maybe a minecraft block so the clues could be "this block is not effected by gravity" which would rule out blocks like sand and gravel.
These clues could be simply scattared about in a scavenger hunt fashion or maybe have them be rewards for smaller scale challenges.
At an appointed time each team will come together and try to use their clues to deduce the combination whichever team gets it gets the loot inside the safe.
Maybe as consolation prizes each clue is bundled with a little treasure so if it turns out you're on the team that doesn't win, atleast you get some goodies to take home. 
The idea might need some work but what do you think?

**Comment by FilidDamhsoir** [comment]
Pretty sure this can be run via staff with no code needed.
What we would need:
-Prizes.
-Probaby a Big safe we can put in spawn to draw intrest
-clues
-a word
I can see this either working with a /lwc password lock on the door to the safe, and then some of pugs "you may only touch once signs"  (and a pug coded way to limit access so that the team who cracks it doesn't then just invite everyone to touch the signs.)  
Or rather than a singe "team" make the reward smaller and let *the whole server* be a single team (no puga-code limits needed, except the "you may only touch once sign)
Or for a more limited version.  Either at a specified time have teams /msg the staff member running it with a pass/fail chance or better option let teams put in a ticket when they think they have it. Then the first staff member on can confirm/deny a winner, since its first team to crack it.
Having a safe means we can pull it back out and run this event again, as frequently/infrequently as we want.
We can have a buy-in cost  "your team must be formed and pay the entry fee by X date/time in order to participate"  (Could be a fee sign that gives out the first clue?)
