### ISSUE TITLE
Quests featherboard

### ISSUE THREAD

**Issue by Pugabyte** [Pugabyte/BearNation#126]
Track information such as current quest, quest objectives, etc. 

[Quester.java#L373](https://github.com/FlyingPikachu/Quests/blob/master/src/main/java/me/blackvein/quests/Quester.java#L373)

**Comment by FilidDamhsoir** [comment]
Originally my thought was to have the current/most recent quest and its current objective (or objective override) display at all times 
But the objectives can be really long, players can now be on multiple quests at once,  and the list displayed (via /quest or in the /quest journal) is based off the order the quests were *created* in, not the order users accepted them, or anything else simple like that.  I don't know if there is a way to capture for display the most recently acquired (incomplete) quest.  But if there is, that would be ideal, along with its current stage requirement or requirement override.  If that means every stage of every quest must have an override manually set, that can be done.
 
Similarly, the /quest list does not sort/remove completed quests, or those the user doesn't meet the requirements to.   Having a display of how many quests a user has currently accepted  sort of like tickets  like 5/38  and how many they have that are available (that are repetable or not yet accepted that they meet the requirements to) would also be nice.  Again, not sure what of this is possible, but it would be idea.

Finally while in quest world, a display listing the users current location by name.  This part should be easy.  Since a ton of regions are going to be made in order to set up mythic mobs for correct spawning, it should just be able to capture/display the current region name like: Brittlestone or 'Avalonlea woods' (it just means we need to remember to give regions names that we want users to see)

So ideally, *while in quest world*  users who toggle on their feathboardboard would see:


------------------------------------
|  Whatever is currently up here  |
| chat and server stuff                 |
| - [N] -- [NE] --- [E]---                |
| current coordinates? maybe     |
| Location:  <Region Name>      |
| Most Recent Quest: <name>    |  <-- most recent *active* quest
| Objective: <words>                  |
| Current Quests :  # out of #      |
| Available Quests:  # out of #    |
|Maybe a reminder ?                   |  Something like 'Use /quest to see all current quests'
------------------------------------

**Comment by FilidDamhsoir** [comment]
John points out it should also have the usual "voice channel" you are in, and maybe your current econ bal in the quest world
