### ISSUE TITLE
QW needs stuff- the master list

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#168]
Submitted by **Filid**

**Comment by FilidDamhsoir** [comment]
Things I know I need for quest world- **Building Edition** :
1. An expandable bank Done! Just needs a place in world and the terraforming to go with.
2. Brittlestone Terraforming and interior- in progress

3. Brittlestone Mine.  /Staffwarps tp Brittlestonemine.  A small mine with a few rooms at the bottom where some NPCs can be trapped by monsters

4.  Some cleanup on the Jail.  Its at /warp jail.   Its mostly good, but I'd like a builder to go over it- eye it for any improvements, clean up where it was being used to test some quest stuff. Then it needs to be world edited to /staffwarps tp jail  and the area terraformed (it doesn't need to go exactly in that spot, but somewhere on that peninsula would be ideal.  Preferably with a path down to the water and a small dock. 

5.  /staffwarps tp QT2, QT3 and QP1.   QT2 and QP1  are supposed to be the town and matching castle- they should be mostly done. QT3 should be done, John did the interior, but I'd like a second set of eyes on it to confirm it's good to go.   There are signs at each warp detailing the changes needed/suggested.  But little things to punch up the interior.
4.  Some cleanup on the Jail.  Its at /warp jail.   Its mostly good, but I'd like a builder to go over it- eye it for any improvements, clean up where it was being used to test some quest stuff. Then it needs to be world edited to /staffwarps tp jail  and the area terraformed (it doesn't need to go exactly in that spot, but somewhere on that peninsula would be ideal.  Preferably with a path down to the water and a small dock. 

5.  /staffwarps tp QT2, QT3 and QP1.   QT2 and QP1  are supposed to be the town and matching castle- they should be mostly done. QT3 should be done, John did the interior, but I'd like a second set of eyes on it to confirm it's good to go.   There are signs at each warp detailing the changes needed/suggested.  But little things to punch up the interior.
6. Staffwarps tp  QT1.  John, Steve, Dayle and Thunder all made similar comments about what needs to be changed there.  If someone besides one of them chooses to tackle it, poke me for a summary of their suggestions.

7.  All the builds for 5 and 6 above need to then be moved into the world and terraformed in place.  I don't know that I've set warps for them yet.  When I do, I will update this section to include warp names

8.  While we are mostly going to use regions to contain folks to set areas, some general pathways,  physical terraforming, bridges and such need to be made in the starting areas.  If you want to take part of this one, let me know and I will set you up with a peice of the map.  I want the world to mostly retain its vanilla feel,  but some improvments can/should be made

This we need for quest world: **NPC Edition**:
1. NPCs in each town:
-BrittleStone
-Avontyre
-Avontyre Castle
-Steve's Little Ice Fishing village
-Shepshed (formerly Padstow)
2. Skins for NPCs- oh god someone please to be finding some skins
3.  Quests set up on NPCs
4.  Do they talk? I hate the proximity talker, but im okay with non-quest npcs still talking when right clicked ala npcs at spawn/hoh.  Obviously not that much- a line or two for lore.  At which point - we need a list of NPCs and their lore. 
5. Mythic Mob non-hostile npcs to populate towns and move around randomly

Things we need for quest world **Everything Else Edition:**
1. Regions set up over each area to name the areas, set mobs, Block entry to off limits (currently) areas.
2.  Mobs.  Every non-vanilla hostile mob  needs to be created in the file, then given which regions they can spawn within
3.  Do we allow vanilla mobs to spawn at all?  If not, all passive mobs also need to be created and given areas to be spawned
4. Items.  Every custom item that isn't a quest reward needs to be created in the Mythic Mobs file, and then assigned to which mob  can drop them
5.  Any admin shop signs for buying/selling goods needs to be placed.  Or they need to be made into quests for interaction.  Admin shop signs are more convent/less annoying for fast sale or basic blocks-both for players and for whoever is setting this up
6.  Any areas where players can "harvest" goods need to be set up so that they regenerate the good in question and prevent players from breaking anything other than what we want them to. 
7.  Bank vaults need the regions like the shops in plaza/mall so that players can "claim" vaults.  Players should be able to place additional chests (purchaseable from a sign/npc) but not make/place crafting tables or the like. 
8.  Town warps need to be set, and decided on.  My initial thought is every town has a warp area.  On reaching a new town that's warp-able the first time, players can talk to a dude, take a quest and do something (maybe as simple as talking to him a second time, or paying some amount of money, maybe doing a small quest) . Part of the quest rewards is the pex permission needed to use that warp forever.

9.  Steves little ice fishing town needs a name.  So do a lot of other places.

10.  Quests maybe needs some sort of update?  I'm getting a message over and over again about something about "language phrases" in console ,  and at least one of the quests I set up today doesn't show after a reload- but shows in the editor
11.  The featherboard. I updated the github on that today.  Its also low prority.  We can launch without it, its just nice to have

**Comment by arbiter6784** [comment]
**Updated List:**

1. **Vinter Gorge, Vinterbite & Vinter Peaks** (the mountains) are completed. 
     - Awaiting NPC placement, Quest Development & Region Assigning (Some areas only)."

2. **Avontyre.** The City itself is complete pending some redesign/reconstruction of certain/specific buildings that do not fit the style of city. The Port requires two more ships, however is mostly complete. /questwarps tp Avontyre

3. **Nyukoroni Region.** The Asian-style town on the North Eatern part of the Continent has been under development. At around 60-70% completion. Town is mostly complete, requires another ship, administration building and pagoda. Surrounding regions require farmland and pastures. /questwarps tp Nyukoroni

4. **All Roads Lead to Avontyre.** The road network for the quest world has had 0 development outside of cities. This will need to be done to connect various points of the QW with one another. I'll work on a rough map and send to Filid.

5. **Smaller Villages/Towns.** As with any good world of questing and adventuring, there needs to be a populace! There will be a need to development some small settlements/trading posts/farms etc. to populate regions of the continent. No more than 3? (3-6 buildings maximum per settlement and likely wont need fleshing out with quests.

6. **TBA Bank Company.** There's a bank that needs to be put down somewhere and given a small settlement to be apart of. 

7. **Archipelago Hermit/Road** North of Avontyre there is an Archipelago that requires construction! This needs an overgrown/not so obvious road from the outskirts of Avontyre all the way north with broken bridges etc. til you reach the edge where a small hermits hut will be needed.

**If anyone would like to help with building or anything QW please talk to either Filid or myself for more information!**
