### ISSUE TITLE
Change more of the McMMO reset rewards to allow players to choose an item to apply it to

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#228]
**Pugabyte**: Archery and Acrobatics at least

**Comment by FilidDamhsoir** [comment]
I know when steve and i did this we had a list of ideas- 2 or 3 alternates wed come up with, some of the suggestions that arc/mason had xome up with that were fesiable, as well as a few others that had been suggested.

I will try to find that list and the ideas that have been said at meetings or in my DMs since when i am home. 

I know it incldues the steve version of a progressive stacking bonus from multipul resets-
Maybe the item you get the first timeyou reset somethign is one only some people would use, but 3 or 4 resets later as it has its properities chabged (trade in your item from last time for the better version)- gold armor becomes iron then diamond, picks up strong effrcts or additional  vanilla enchantslile unbreaking and protection and such. So that it winds up going from a balanced "some people will want this, some people would rather keep their 100 mcmmo and its passive bonus" to something worth the effort of having given up 500 or more BN mcmmo levels

**Comment by FilidDamhsoir** [comment]
After talking with players who matter- ie those who frequently use this:


Acro- Boots. Buff? Gears 3 (already fixed i think) add  feather falling and mending
Alchemy- Potion lobber and /stack.  Do not change
Archery- Weak ass bow. Boost or repalace. Add infinty and Mending
Axes- Add mending to current axe
Excavation- Diamond shovel- Eff 5, Unbreak 3, Silk touch, mending 
Fishing- Rod.  Maybe buff? Luck to 5, add Unbreak9ing 3, remove fire aspect
Herbalism- Wakka's auto bonemeal boots instead? maybe? if they work?
Mining - /glowing on helmet. Very popular. Much keep
Repair- Auto repair. Do not remove
Swords- Adds Sharp 2. Looting 2. Mending
Taming- Horse Picker. Keep
Unarmed- Bandage and stick with disarming 1 ("Quarterstaff")
Woodcutting- Buff axe to energize 3.  Also leather helmet with implants 1
And mending and Enlighted 1 to the chestplate for the all reset


In additon, raise level cap to 200 and double the money prize.  

Currentl;y waiting on wakka/pug to complete the boots, and approve the rest of it
