### ISSUE TITLE
Blast mining mcMMO drops PStones

### ISSUE THREAD

**Issue by WakkaFlocka239** [Pugabyte/BearNation#250]
Using blast mining from mcmmo drops psstone ores, it should instead drop the ingots.

**Comment by FilidDamhsoir** [comment]
I looked into the mcMMO config to see if this could be changed the easy way.  All mcMMO does with this is increase the percentage of ore drops.  I could set all of them to 0 and we'd still get some ore drops because that's a vanilla behavior- which means I think a skript to change the vanilla behavior (similar to the one for silk touch) in the first place would fix this maybe?

**Comment by WakkaFlocka239** [comment]
I think the code I just wrote overrides anything mcMMO does, so changing it _shouldn't_ effect anything now. 
The skript waits for an explosion event, and loops the exploded blocks, and if the block is a pstone ore, then it does the same thing as pssilk: sets the block to air, drops the correct ingots with exp their specified XP per exploded block.
