### ISSUE TITLE
lwc not working properly with doors

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#375]
**Camaros**: Doors intermittently stop working. If somebody wants to get through a door, if they try and open it enough times, it'll eventually open. Not sure if this is also an issue with chests or not.

**Comment by Shannontc** [comment]
It appears that chests are still fine. It only seems to happen with doors that have already been created in the legacy survival world.

**Comment by Pugabyte** [comment]
CNR
- Was the server lagging?
- Are you sure it wasnt client side? 
- Do you have a specific door it happens on?

**Comment by Shannontc** [comment]
I believe this was happening more often when the server was still lagging. I can say 100% it was not client side, because I could get a locked door to finally open on an account that does not have access to that door and could actually walk through that door. I could then no longer close the door because it would tell me that it is locked. It happens with the doors at my home (/home Camaros home). I have tested new doors in both legacy and 1.15.2 survival world, along with chests in the legacy world, and the issue appears to only be with existing doors in legacy world.

**Comment by Shannontc** [comment]
https://www.youtube.com/watch?v=Y-UiENQhH2I
You can see here that it will say the doors are not locked and then say they are locked again.

**Comment by Pugabyte** [comment]
This is caused by the top not being locked, while the bottom is locked

**Comment by Pugabyte** [comment]
Will track issue at https://github.com/pop4959/LWCX/issues/107
