### ISSUE TITLE
Death Swap Issues

### ISSUE THREAD

**Issue by ThunderShockBN** [Pugabyte/BearNation#439]
- [x] -Starting a new match should reset the daylight cycle to morning.

- [x] -Phantoms should be disabled or their 3 day spawning requirement should be reset at the start of a match.

- [x] -Cmodify is still enabled meaning you can't steal the opposing players' chests and furnaces.

- [x] -Maybe mob griefing should be enabled? 

- [x] -If ladders are going to be banned, so should trap doors.

- [x] -Maybe double the world border size and put a region down the center that prevents entry; essentially keeping them separate so they can't just PVP them to death. 

- [x] -In the lobby while you wait for the game to start, you can PVP each other.

- [x] -Maybe add a 3 second count down before the swap? I've some versions of DS use that and it can prevent the game from dragging on.

- [x] -Maybe add a minimum time limit before a random swap can happen, like 30 seconds.

**Comment by Blast-MC** [comment]
@ThunderShockBN Should pvp be disabled all together? That’s easier to handle than regions if that’s what you want

**Comment by lexikiq** [comment]
> -Phantoms should be disabled or their 3 day spawning requirement should be reset at the start of a match.

phantoms should just be disabled entirely-- the matches are only 30 minutes max and there's no way you'd get through 3 nights in that time

> -Maybe double the world border size and put a region down the center that prevents entry; essentially keeping them separate so they can't just PVP them to death.

i personally like having the option of being able to sneakily hunt people down and kill them (keeps you on your toes!), though i can see that being against the nature of the game.

side note, the game supports any number of players so this wouldn't work, better idea would just be setting pvp to off in the global worldguard region.

> -If ladders are going to be banned, so should trap doors.

hard disagree. ladders were banned because players sometimes loaded into their new position before the ladders loaded, so even if you were crouching, you'd fall to your death on occasion, making it an unstoppable trap. trapdoors aren't climbable and thus don't present the same issues as ladders.

> -Maybe add a 3 second count down before the swap? I've some versions of DS use that and it can prevent the game from dragging on.

i'm not opposed to this as long as players have more prep time at the start of the match (before the first swap) to get iron to survive falls. (if this is added then ladders should probably be unbanned too :p)

unrelated, but: petition to add the nether :)

**Comment by lexikiq** [comment]
you can break blocks in the lobby
