### ISSUE TITLE
[Needs Discussion] Infection variant where Humans kill Zombies easier

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#88]
**Noahkiq**: [8:07 PM] Noahkiq: maybe give both teams similar weapons but give zombies a little extra health
[8:07 PM] Noahkiq: and dont give em jump boost/speed until half-way through the game
[8:07 PM] Noahkiq: iunno. i'd personally have more fun in a game that's a little more balanced and doesn't soley depend on finding the easiest spot to shoot people from

**Comment by BearNationSMP** [comment]
**Noahkiq**: | possibly give human players a barricade to create more strategic spots (ie give player iron door, zombies get some pickaxe to break it)? would be used to protect them from zombies, and maybe in rare circumstances, allow them to get up higher. (probably would have to be done in a way where zombies can still get to the spot from other locations using parkour. or we could prevent the humans from breaking their doors so the zombies could use them too.)

**Comment by JustSteveThings** [comment]
Okay so i've been looking at this and the 1st ever infection supported this "game style" without the bonus health or item placement it used to be mars camp the original game mode for infection and it work out okay for a beta test but we came to really realize that the humans are able to easily farm the zombies at their spawn. It took a long time of testing and adding the right amount of advantages which as you've seen its the speed and jump to really forge the game mode as we play  today. 

We've also tried to change the style of infection completely with different attempts that ended up in fails one of the more publicly known ideas was the blind slow tank zombies in what is know known as village, but that wasn't the 1st of the game mode alters that we attempted, we've tried to do it with less speed and no jump, we also tried to give zombies a smaller less painful punch bow, we've tried to add other potions types like but not limited to one combo of night vision, invisibility, water breathing. We also tried to use no bows on the humans and have them potions and a stronger weapon and some mid range Armour like iron i could go on but i think i've proved my point . I'm willing to re-discuss the topic but i hold my judgement due to the previous attempts and the out roar of hate when we tried to play the infection version of village. I personally believe that infection had be defined and those who enjoy it like its current set up, not many people like when a game type is changed.
