### ISSUE TITLE
[Needs Discussion] 1.9 PVP in Minigames

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#92]
**Noahkiq**: i think we've been using 1.8 PVP for long enough... if we're going to do this, it should be on all minigames at the same time so we don't have players confused about what games use what version of pvp

**Comment by FilidDamhsoir** [comment]
1.9 PvP was pretty well hated by players and staff, and changed game balance in a number of games to even more favor the bow spam bitches. Now some of that was it being new and now players are used to it in survival but personally I'd still like it to die in a fire.  

This is one where I would like to see feedback now just from staff but also players before we even co sided this switch. Otherwise, since most of our fan favorites (and most of the mini games in general) are 1.8, those that arnt could be switched  to keep it consistant.

**Comment by JustSteveThings** [comment]
I honestly don't know. I've often said we should make it more Pro 1.12 PvP because it's the current combat system but either way we do it. As long as we let the players know 1st.  I don't like the concept of some old then the rest been new combat because it'll fuck with peoples minds between games so its an all or nothing idea
