### ISSUE TITLE
Command to show enchants in chat

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#97]
Suggested by PonyoBear

**Comment by WakkaFlocka239** [comment]
Maybe look into something like this?
[https://www.spigotmc.org/resources/chatitem-display-items-in-chat.19064/](https://www.spigotmc.org/resources/chatitem-display-items-in-chat.19064/)
Uses config-defined placeholders like '{i}' to show the item that you're holding using json to make it look like the actual items hoverable text in your inventory, but in chat. 
Instead of listing out each enchantment in chat or whatnot, it makes it super compact, and fancy.
